/// Asset integrity verifier.
///
/// Walks assets/arasaac/manifest.json and recomputes SHA-256 for every
/// entry's icon_uri on disk, plus a small fixed set of brand assets
/// (the Foundation mark + the in-app Lighthouse mark) and every TTS clip in
/// assets/audio/manifest.json. Fails (exit 1) on any mismatch, missing file,
/// orphaned manifest entry, or asset not actually bundled by pubspec.yaml.
///
/// Run from the repo root:
///   dart run tools/verify_assets.dart
///
/// CI should run this as a pre-build step. See ADR 0001 (asset licensing)
/// "Integrity policy (Phase 2)" and assets/arasaac/manifest.json's
/// checksum_policy block.
///
/// NOTE: the platform launcher icons under android/ and ios/ are NOT
/// checksummed here. They are regenerated by flutter_launcher_icons from
/// tools/branding/ and legitimately change; the source of truth for
/// those is tools/branding/. This verifier covers only the runtime-
/// bundled assets/brand/ marks, which are stable.
library;

import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

/// Runtime-bundled brand assets (assets/brand/), keyed by path to the
/// expected SHA-256. Update intentionally when a mark is replaced.
const Map<String, String> _brandAssets = {
  'assets/brand/kinder-horizon-mark.png':
      'e4d70e74950cbac9a196b02e8b8c9fe7da7e610f792e99dbaf6b5f1084452b0a',
  'assets/brand/lighthouse-mark.png':
      '5765b98a353b51b508dc1ba7489cb0bbd143bdbabbaff866d0ab0580c6711724',
};

Future<void> main(List<String> args) async {
  final root = Directory.current.path;
  final manifestFile = File('$root/assets/arasaac/manifest.json');
  if (!manifestFile.existsSync()) {
    stderr.writeln('verify_assets: manifest not found at ${manifestFile.path}');
    exit(1);
  }

  final manifest =
      jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final symbols = (manifest['symbols'] as List).cast<Map<String, dynamic>>();

  var mismatch = 0;
  var missing = 0;
  var ok = 0;

  Future<void> check(String uri, String? expected) async {
    if (expected == null || expected.isEmpty) {
      stderr.writeln('verify_assets: $uri has no expected sha256');
      mismatch++;
      return;
    }
    final file = File('$root/$uri');
    if (!file.existsSync()) {
      stderr.writeln('verify_assets: missing on disk: $uri');
      missing++;
      return;
    }
    final actual = sha256.convert(await file.readAsBytes()).toString();
    if (actual != expected) {
      stderr.writeln('verify_assets: sha256 MISMATCH for $uri');
      stderr.writeln('  expected: $expected');
      stderr.writeln('  actual:   $actual');
      mismatch++;
      return;
    }
    ok++;
  }

  for (final entry in symbols) {
    await check(entry['icon_uri'] as String, entry['sha256'] as String?);
  }
  for (final brand in _brandAssets.entries) {
    await check(brand.key, brand.value);
  }

  // Bundling-gap check. A checksum-correct, on-disk-present pictogram is
  // still useless if pubspec.yaml does not actually bundle it: Flutter
  // asset directory entries are non-recursive, so listing `assets/arasaac/`
  // ships the manifest but none of the nested category PNGs, and every tile
  // renders symbol-less. This caught exactly that regression. We assert each
  // manifest icon_uri is covered by the declared asset list, using Flutter's
  // own bundling semantics: a file is bundled iff its exact path is listed
  // OR its IMMEDIATE parent directory (trailing slash) is listed. An ancestor
  // directory does not count, because directory entries do not recurse.
  final declared = _declaredAssetEntries(File('$root/pubspec.yaml'));
  var notBundled = 0;
  for (final entry in symbols) {
    final uri = entry['icon_uri'] as String;
    final parentDir = '${_dirname(uri)}/';
    if (!declared.contains(uri) && !declared.contains(parentDir)) {
      stderr.writeln('verify_assets: NOT BUNDLED by pubspec.yaml: $uri');
      stderr.writeln('  add `- $parentDir` (or `- $uri`) under flutter/assets');
      notBundled++;
    }
  }

  // Audio clip manifest (docs/adr/0004 amendment). Same discipline as the
  // pictograms: every committed clip must checksum-match on disk AND be bundled
  // by pubspec.yaml. The manifest always ships; an empty clips[] (no audio
  // generated yet) passes trivially. The per-locale clip directories live one
  // level under assets/audio/, so the non-recursive bundling trap applies here
  // exactly as it does for ARASAAC categories.
  final audioManifestFile = File('$root/assets/audio/manifest.json');
  if (!audioManifestFile.existsSync()) {
    stderr.writeln(
        'verify_assets: audio manifest not found at ${audioManifestFile.path}');
    exit(1);
  }
  final audioManifest =
      jsonDecode(audioManifestFile.readAsStringSync()) as Map<String, dynamic>;
  final clips =
      ((audioManifest['clips'] as List?) ?? const []).cast<Map<String, dynamic>>();
  for (final clip in clips) {
    await check(clip['path'] as String, clip['sha256'] as String?);
  }
  for (final clip in clips) {
    final uri = clip['path'] as String;
    final parentDir = '${_dirname(uri)}/';
    if (!declared.contains(uri) && !declared.contains(parentDir)) {
      stderr.writeln('verify_assets: NOT BUNDLED by pubspec.yaml: $uri');
      stderr.writeln('  add `- $parentDir` (or `- $uri`) under flutter/assets');
      notBundled++;
    }
  }

  // Orphan-clip check. Stale renders (a word that got relabelled or re-voiced)
  // leave .mp3 files on disk that the manifest no longer references. The engine
  // never plays them, but pubspec bundles the whole assets/audio/<locale>/ dir,
  // so they ship as dead weight and the on-disk count silently drifts from the
  // manifest. The checks above are blind to extra files (they only verify that
  // manifest entries exist), so enumerate the audio tree and fail on any clip
  // not referenced by the manifest.
  final referenced = {for (final c in clips) c['path'] as String};
  var orphan = 0;
  final audioDir = Directory('$root/assets/audio');
  if (audioDir.existsSync()) {
    for (final f in audioDir.listSync(recursive: true).whereType<File>()) {
      if (!f.path.endsWith('.mp3')) continue;
      final rel = f.path.substring(root.length + 1);
      if (!referenced.contains(rel)) {
        stderr.writeln('verify_assets: ORPHAN clip (not in manifest): $rel');
        orphan++;
      }
    }
  }

  stdout.writeln('verify_assets: ok=$ok mismatch=$mismatch missing=$missing '
      'notBundled=$notBundled orphan=$orphan (clips=${clips.length})');
  if (mismatch > 0 || missing > 0 || notBundled > 0 || orphan > 0) exit(1);
}

/// POSIX-style dirname (icon_uri values are forward-slash asset paths).
String _dirname(String path) {
  final i = path.lastIndexOf('/');
  return i < 0 ? '' : path.substring(0, i);
}

/// Extracts the asset entries declared under `flutter: > assets:` in
/// pubspec.yaml, without a YAML dependency. Returns the raw entry strings
/// (file paths and trailing-slash directory paths) exactly as written.
Set<String> _declaredAssetEntries(File pubspec) {
  if (!pubspec.existsSync()) {
    stderr.writeln('verify_assets: pubspec.yaml not found for bundling check');
    exit(1);
  }
  final lines = pubspec.readAsLinesSync();
  final entries = <String>{};
  var inAssets = false;
  var assetsIndent = -1;
  for (final raw in lines) {
    final line = raw.replaceAll('\t', '  ');
    if (line.trim().isEmpty || line.trimLeft().startsWith('#')) continue;
    final indent = line.length - line.trimLeft().length;
    final trimmed = line.trim();

    if (!inAssets) {
      if (trimmed == 'assets:') {
        inAssets = true;
        assetsIndent = indent;
      }
      continue;
    }

    // A list item belonging to the assets block.
    if (trimmed.startsWith('- ') && indent > assetsIndent) {
      entries.add(trimmed.substring(2).trim());
      continue;
    }
    // Any non-list line at or below the assets: indent ends the block.
    if (indent <= assetsIndent) break;
  }
  return entries;
}
