/// OTA signing tooling round-trip (ADR 0017).
///
/// The contract test for tools/ota: a key pair generated by the tool, used to
/// sign manifest bytes, must verify under the app's REAL
/// [ManifestSignatureVerifier]. If the on-device verifier ever changes what it
/// accepts (key length, algorithm, byte handling), this breaks here, before any
/// content is published that the installed app would reject.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:lighthouse/services/ota/ota.dart';

import '../../tools/ota/ota_signing.dart';

void main() {
  test('generated key signs a manifest the app verifier accepts', () async {
    final pair = await generateKeyPair();
    expect(pair.seed.length, 32);
    expect(pair.publicKey.length, 32);

    final manifestBytes = utf8.encode(
      '{"schemaVersion":1,"sequence":3,"contentVersion":"2026.05.31","files":[]}',
    );
    final signature = await signManifestBytes(pair.seed, manifestBytes);

    final verifier = ManifestSignatureVerifier(
      trustedPublicKeysBase64: [base64.encode(pair.publicKey)],
    );
    expect(
      await verifier.verify(
          manifestBytes: manifestBytes, signatureBytes: signature),
      isTrue,
    );
  });

  test('a different key in the trust-list does NOT verify (fails closed)',
      () async {
    final signer = await generateKeyPair();
    final other = await generateKeyPair();

    final manifestBytes = utf8.encode('{"schemaVersion":1,"sequence":1}');
    final signature = await signManifestBytes(signer.seed, manifestBytes);

    final verifier = ManifestSignatureVerifier(
      trustedPublicKeysBase64: [base64.encode(other.publicKey)],
    );
    expect(
      await verifier.verify(
          manifestBytes: manifestBytes, signatureBytes: signature),
      isFalse,
    );
  });

  test('a tampered manifest byte breaks verification', () async {
    final pair = await generateKeyPair();
    final manifestBytes =
        Uint8List.fromList(utf8.encode('{"sequence":7,"x":"original"}'));
    final signature = await signManifestBytes(pair.seed, manifestBytes);

    final tampered = Uint8List.fromList(manifestBytes)
      ..[manifestBytes.length - 2] ^= 0x01;

    final verifier = ManifestSignatureVerifier(
      trustedPublicKeysBase64: [base64.encode(pair.publicKey)],
    );
    expect(
      await verifier.verify(
          manifestBytes: tampered, signatureBytes: signature),
      isFalse,
    );
  });

  test('signManifestBytes rejects a malformed seed', () async {
    expect(
      () => signManifestBytes(const [1, 2, 3], utf8.encode('{}')),
      throwsArgumentError,
    );
  });
}
